config/routes.rb
Bamot::Application.routes.draw do
  resources :creations

  resources :kinds

  resources :extfiles

  resources :topics

  resources :garins

  resources :grades

  devise_for :users
  resources :users, :only => [:index, :show]

  root :to => "home#index"

  match "creations/:id/comment" => "creations#comment"

  match 'submit', :to => 'creations#new'
  match 'about', :to => 'home#about'
  match 'search', :to => 'home#search'
  match 'news', :to => 'home#news'
  match 'notify', :to => 'users#notify'
end

app/models/kind.rb
class Kind < ActiveRecord::Base
  has_many :creations
  has_friendly_id :name, :use_slug => true

  def fullname
    name+" - "+description
  end
end

app/controllers/kinds_controller.rb
class KindsController < ApplicationController

  before_filter :admin, :except => [:show]

  # GET /kinds
  # GET /kinds.xml
  def index
    @kinds = Kind.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @kinds }
    end
  end

  # GET /kinds/1
  # GET /kinds/1.xml
  def show
    @kind = Kind.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @kind }
    end
  end

  # GET /kinds/new
  # GET /kinds/new.xml
  def new
    @kind = Kind.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @kind }
    end
  end

  # GET /kinds/1/edit
  def edit
    @kind = Kind.find(params[:id])
  end

  # POST /kinds
  # POST /kinds.xml
  def create
    @kind = Kind.new(params[:kind])

    respond_to do |format|
      if @kind.save
        format.html { redirect_to(@kind, :notice => 'Kind was successfully created.') }
        format.xml  { render :xml => @kind, :status => :created, :location => @kind }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @kind.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /kinds/1
  # PUT /kinds/1.xml
  def update
    @kind = Kind.find(params[:id])

    respond_to do |format|
      if @kind.update_attributes(params[:kind])
        format.html { redirect_to(@kind, :notice => 'Kind was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @kind.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /kinds/1
  # DELETE /kinds/1.xml
  def destroy
    @kind = Kind.find(params[:id])
    @kind.destroy

    respond_to do |format|
      format.html { redirect_to(kinds_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/views/kinds/_form.html.erb
<%= form_for(@kind) do |f| %>
  <% if @kind.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kind.errors.count, "error") %> prohibited this kind from being saved:</h2>

      <ul>
      <% @kind.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kinds/edit.html.erb
<h1>Editing kind</h1>

<%= render 'form' %>

<%= link_to 'Show', @kind %> |
<%= link_to 'Back', kinds_path %>

app/views/kinds/index.html.erb
<h1>Listing kinds</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @kinds.each do |kind| %>
  <tr>
    <td><%= kind.name %></td>
    <td><%= kind.description %></td>
    <td><%= kind.content %></td>
    <td><%= link_to 'Show', kind %></td>
    <td><%= link_to 'Edit', edit_kind_path(kind) %></td>
    <td><%= link_to 'Destroy', kind, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Kind', new_kind_path %>

app/views/kinds/new.html.erb
<h1>New kind</h1>

<%= render 'form' %>

<%= link_to 'Back', kinds_path %>

app/views/kinds/show.html.haml
%div.span-24
  .span-6.last(style="float: right;")
    %h2= @kind.name
    %h3= @kind.description
    .moreover
      :textile
        #{@kind.content}
  - @kind.creations.each do |creation|
    %div.span-6.space
      %h3(class="farline")
        =link_to(creation.name, "/creations/"+creation.friendly_id+"?context=kind")
        %sub!= creation.user.display_name
      %p
        - if creation.image?
          =link_to(image_tag(creation.image.url(:medium), {'style'=>'-webkit-box-shadow: black 0px 0px 1px;'}), "/creations/"+creation.friendly_id+"?context=kind")
        :textile
          #{creation.summary}