config/routes.rb
Bamot::Application.routes.draw do
  resources :creations

  resources :kinds

  resources :extfiles

  resources :topics

  resources :garins

  resources :grades

  devise_for :users
  resources :users, :only => [:index, :show]

  root :to => "home#index"

  match "creations/:id/comment" => "creations#comment"

  match 'submit', :to => 'creations#new'
  match 'about', :to => 'home#about'
  match 'search', :to => 'home#search'
  match 'news', :to => 'home#news'
  match 'notify', :to => 'users#notify'
end

app/models/extfile.rb
class Extfile < ActiveRecord::Base
end

app/controllers/extfiles_controller.rb
class ExtfilesController < ApplicationController
  # GET /extfiles
  # GET /extfiles.xml
  def index
    @extfiles = Extfile.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @extfiles }
    end
  end

  # GET /extfiles/1
  # GET /extfiles/1.xml
  def show
    @extfile = Extfile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @extfile }
    end
  end

  # GET /extfiles/new
  # GET /extfiles/new.xml
  def new
    @extfile = Extfile.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @extfile }
    end
  end

  # GET /extfiles/1/edit
  def edit
    @extfile = Extfile.find(params[:id])
  end

  # POST /extfiles
  # POST /extfiles.xml
  def create
    @extfile = Extfile.new(params[:extfile])

    respond_to do |format|
      if @extfile.save
        format.html { redirect_to(@extfile, :notice => 'Extfile was successfully created.') }
        format.xml  { render :xml => @extfile, :status => :created, :location => @extfile }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @extfile.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /extfiles/1
  # PUT /extfiles/1.xml
  def update
    @extfile = Extfile.find(params[:id])

    respond_to do |format|
      if @extfile.update_attributes(params[:extfile])
        format.html { redirect_to(@extfile, :notice => 'Extfile was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @extfile.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /extfiles/1
  # DELETE /extfiles/1.xml
  def destroy
    @extfile = Extfile.find(params[:id])
    @extfile.destroy

    respond_to do |format|
      format.html { redirect_to(extfiles_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/extfiles_helper.rb
module ExtfilesHelper
end

app/views/extfiles/_form.html.erb
<%= form_for(@extfile) do |f| %>
  <% if @extfile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@extfile.errors.count, "error") %> prohibited this extfile from being saved:</h2>

      <ul>
      <% @extfile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :path %><br />
    <%= f.text_area :path %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/extfiles/edit.html.erb
<h1>Editing extfile</h1>

<%= render 'form' %>

<%= link_to 'Show', @extfile %> |
<%= link_to 'Back', extfiles_path %>

app/views/extfiles/index.html.erb
<h1>Listing extfiles</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Path</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @extfiles.each do |extfile| %>
  <tr>
    <td><%= extfile.name %></td>
    <td><%= extfile.path %></td>
    <td><%= link_to 'Show', extfile %></td>
    <td><%= link_to 'Edit', edit_extfile_path(extfile) %></td>
    <td><%= link_to 'Destroy', extfile, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Extfile', new_extfile_path %>

app/views/extfiles/new.html.erb
<h1>New extfile</h1>

<%= render 'form' %>

<%= link_to 'Back', extfiles_path %>

app/views/extfiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @extfile.name %>
</p>

<p>
  <b>Path:</b>
  <%= @extfile.path %>
</p>


<%= link_to 'Edit', edit_extfile_path(@extfile) %> |
<%= link_to 'Back', extfiles_path %>