config/routes.rb
Bamot::Application.routes.draw do
  resources :creations

  resources :kinds

  resources :extfiles

  resources :topics

  resources :garins

  resources :grades

  devise_for :users
  resources :users, :only => [:index, :show]

  root :to => "home#index"

  match "creations/:id/comment" => "creations#comment"

  match 'submit', :to => 'creations#new'
  match 'about', :to => 'home#about'
  match 'search', :to => 'home#search'
  match 'news', :to => 'home#news'
  match 'notify', :to => 'users#notify'
end

app/models/garin.rb
class Garin < ActiveRecord::Base
  belongs_to :grade
  has_many :users
  has_friendly_id :name, :use_slug => true
end

app/controllers/garins_controller.rb
class GarinsController < ApplicationController

  before_filter :admin, :except => [:index, :show]

  # GET /garins
  # GET /garins.xml
  def index
    @garins = Garin.all
    puts cookies
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @garins }
    end
  end

  # GET /garins/1
  # GET /garins/1.xml
  def show
    @garin = Garin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @garin }
    end
  end

  # GET /garins/new
  # GET /garins/new.xml
  def new
    @garin = Garin.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @garin }
    end
  end

  # GET /garins/1/edit
  def edit
    @garin = Garin.find(params[:id])
  end

  # POST /garins
  # POST /garins.xml
  def create
    @garin = Garin.new(params[:garin])

    respond_to do |format|
      if @garin.save
        format.html { redirect_to(@garin, :notice => 'Garin was successfully created.') }
        format.xml  { render :xml => @garin, :status => :created, :location => @garin }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @garin.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /garins/1
  # PUT /garins/1.xml
  def update
    @garin = Garin.find(params[:id])

    respond_to do |format|
      if @garin.update_attributes(params[:garin])
        format.html { redirect_to(@garin, :notice => 'Garin was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @garin.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /garins/1
  # DELETE /garins/1.xml
  def destroy
    @garin = Garin.find(params[:id])
    @garin.destroy

    respond_to do |format|
      format.html { redirect_to(garins_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/garins_helper.rb
module GarinsHelper
end

app/views/garins/_form.html.erb
<%= form_for(@garin) do |f| %>
  <% if @garin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@garin.errors.count, "error") %> prohibited this garin from being saved:</h2>

      <ul>
      <% @garin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :grade_id %><br />
    <%= f.text_field :grade_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/garins/edit.html.erb
<h1>Editing garin</h1>

<%= render 'form' %>

<%= link_to 'Show', @garin %> |
<%= link_to 'Back', garins_path %>

app/views/garins/index.html.erb
<h1>Listing garins</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Grade</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @garins.each do |garin| %>
  <tr>
    <td><%= garin.name %></td>
    <td><%= garin.grade_id %></td>
    <td><%= link_to 'Show', garin %></td>
    <td><%= link_to 'Edit', edit_garin_path(garin) %></td>
    <td><%= link_to 'Destroy', garin, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Garin', new_garin_path %>

app/views/garins/new.html.erb
<h1>New garin</h1>

<%= render 'form' %>

<%= link_to 'Back', garins_path %>

app/views/garins/show.html.haml
%div.span-20
  %h2
    = @garin.name
    %sub= @garin.grade.name

  - @garin.users.each do |user|
    .creation.space
      %h3
        = link_to(user.fullname, "/users/"+user.friendly_id)